import "../../app/globals.css";

export const metadata = {
  title: "Publico",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    
      <div>
      <h1>Public</h1>  
        {children}
        
        
      </div>
    
  );
}
